// Generated from characters/cut/manifest.json: each character's stickers (picture only, ON12). Labels are for screen readers.
export const STICKERS: Record<string, { id: string; src: number; label: string }[]> = {
  yazan: [
    { id: 'yazan-01', src: require('../../assets/stickers/yazan-01.png'), label: "Hi there" },
    { id: 'yazan-02', src: require('../../assets/stickers/yazan-02.png'), label: "Graduated!" },
    { id: 'yazan-03', src: require('../../assets/stickers/yazan-03.png'), label: "Need coffee" },
    { id: 'yazan-04', src: require('../../assets/stickers/yazan-04.png'), label: "Nice one" },
    { id: 'yazan-05', src: require('../../assets/stickers/yazan-05.png'), label: "Wait, what?" },
    { id: 'yazan-06', src: require('../../assets/stickers/yazan-06.png'), label: "No way!" },
    { id: 'yazan-07', src: require('../../assets/stickers/yazan-07.png'), label: "Zzz" },
    { id: 'yazan-08', src: require('../../assets/stickers/yazan-08.png'), label: "Yes!" },
  ],
  yara: [
    { id: 'yara-01', src: require('../../assets/stickers/yara-01.png'), label: "Seriously?" },
    { id: 'yara-02', src: require('../../assets/stickers/yara-02.png'), label: "Actually..." },
    { id: 'yara-03', src: require('../../assets/stickers/yara-03.png'), label: "Coffee first" },
    { id: 'yara-04', src: require('../../assets/stickers/yara-04.png'), label: "Long shift" },
    { id: 'yara-05', src: require('../../assets/stickers/yara-05.png'), label: "You!" },
    { id: 'yara-06', src: require('../../assets/stickers/yara-06.png'), label: "Love that" },
    { id: 'yara-07', src: require('../../assets/stickers/yara-07.png'), label: "Told you" },
    { id: 'yara-08', src: require('../../assets/stickers/yara-08.png'), label: "Oh no" },
  ],
  omar: [
    { id: 'omar-01', src: require('../../assets/stickers/omar-01.png'), label: "Need coffee" },
    { id: 'omar-02', src: require('../../assets/stickers/omar-02.png'), label: "Nervous" },
    { id: 'omar-03', src: require('../../assets/stickers/omar-03.png'), label: "Still studying" },
    { id: 'omar-04', src: require('../../assets/stickers/omar-04.png'), label: "Panic!" },
    { id: 'omar-05', src: require('../../assets/stickers/omar-05.png'), label: "Nice!" },
    { id: 'omar-06', src: require('../../assets/stickers/omar-06.png'), label: "Facepalm" },
    { id: 'omar-07', src: require('../../assets/stickers/omar-07.png'), label: "Love it" },
    { id: 'omar-08', src: require('../../assets/stickers/omar-08.png'), label: "Mic drop" },
  ],
  layla: [
    { id: 'layla-01', src: require('../../assets/stickers/layla-01.png'), label: "Hehe" },
    { id: 'layla-02', src: require('../../assets/stickers/layla-02.png'), label: "Waaah" },
    { id: 'layla-03', src: require('../../assets/stickers/layla-03.png'), label: "Zzz" },
    { id: 'layla-04', src: require('../../assets/stickers/layla-04.png'), label: "Hmph" },
    { id: 'layla-05', src: require('../../assets/stickers/layla-05.png'), label: "Oh!" },
    { id: 'layla-06', src: require('../../assets/stickers/layla-06.png'), label: "Mwah" },
    { id: 'layla-07', src: require('../../assets/stickers/layla-07.png'), label: "Yay!" },
    { id: 'layla-08', src: require('../../assets/stickers/layla-08.png'), label: "Hi!" },
  ],
  atlas: [
    { id: 'atlas-01', src: require('../../assets/stickers/atlas-01.png'), label: "Ha!" },
    { id: 'atlas-02', src: require('../../assets/stickers/atlas-02.png'), label: "Coffee time" },
    { id: 'atlas-03', src: require('../../assets/stickers/atlas-03.png'), label: "Good job" },
    { id: 'atlas-04', src: require('../../assets/stickers/atlas-04.png'), label: "Ugh" },
    { id: 'atlas-05', src: require('../../assets/stickers/atlas-05.png'), label: "Hmm..." },
    { id: 'atlas-06', src: require('../../assets/stickers/atlas-06.png'), label: "Proud of you" },
    { id: 'atlas-07', src: require('../../assets/stickers/atlas-07.png'), label: "Wake me later" },
    { id: 'atlas-08', src: require('../../assets/stickers/atlas-08.png'), label: "Hello" },
  ],
  nova: [
    { id: 'nova-01', src: require('../../assets/stickers/nova-01.png'), label: "Hmm, sure" },
    { id: 'nova-02', src: require('../../assets/stickers/nova-02.png'), label: "Yay!" },
    { id: 'nova-03', src: require('../../assets/stickers/nova-03.png'), label: "Headache" },
    { id: 'nova-04', src: require('../../assets/stickers/nova-04.png'), label: "You!" },
    { id: 'nova-05', src: require('../../assets/stickers/nova-05.png'), label: "Mwah" },
    { id: 'nova-06', src: require('../../assets/stickers/nova-06.png'), label: "I knew it" },
    { id: 'nova-07', src: require('../../assets/stickers/nova-07.png'), label: "Bye-bye" },
    { id: 'nova-08', src: require('../../assets/stickers/nova-08.png'), label: "Sip" },
    { id: 'nova-09', src: require('../../assets/stickers/nova-09.png'), label: "In love" },
  ],
  bolt: [
    { id: 'bolt-01', src: require('../../assets/stickers/bolt-01.png'), label: "Chill" },
    { id: 'bolt-02', src: require('../../assets/stickers/bolt-02.png'), label: "Whatever" },
    { id: 'bolt-03', src: require('../../assets/stickers/bolt-03.png'), label: "..." },
    { id: 'bolt-04', src: require('../../assets/stickers/bolt-04.png'), label: "Heh" },
    { id: 'bolt-05', src: require('../../assets/stickers/bolt-05.png'), label: "Really?" },
    { id: 'bolt-06', src: require('../../assets/stickers/bolt-06.png'), label: "Slow clap" },
    { id: 'bolt-07', src: require('../../assets/stickers/bolt-07.png'), label: "Zzz" },
    { id: 'bolt-08', src: require('../../assets/stickers/bolt-08.png'), label: "Mic drop" },
  ],
  iris: [
    { id: 'iris-01', src: require('../../assets/stickers/iris-01.png'), label: "Whoa!" },
    { id: 'iris-02', src: require('../../assets/stickers/iris-02.png'), label: "Oops" },
    { id: 'iris-03', src: require('../../assets/stickers/iris-03.png'), label: "Noted" },
    { id: 'iris-04', src: require('../../assets/stickers/iris-04.png'), label: "Grr" },
    { id: 'iris-05', src: require('../../assets/stickers/iris-05.png'), label: "So sad" },
    { id: 'iris-06', src: require('../../assets/stickers/iris-06.png'), label: "Pretty please" },
    { id: 'iris-07', src: require('../../assets/stickers/iris-07.png'), label: "Peace" },
    { id: 'iris-08', src: require('../../assets/stickers/iris-08.png'), label: "Sleepy" },
  ],
  pip: [
    { id: 'pip-01', src: require('../../assets/stickers/pip-01.png'), label: "LOL" },
    { id: 'pip-02', src: require('../../assets/stickers/pip-02.png'), label: "So sad" },
    { id: 'pip-03', src: require('../../assets/stickers/pip-03.png'), label: "Sleepy" },
    { id: 'pip-04', src: require('../../assets/stickers/pip-04.png'), label: "Grr" },
    { id: 'pip-05', src: require('../../assets/stickers/pip-05.png'), label: "Fixed it!" },
    { id: 'pip-06', src: require('../../assets/stickers/pip-06.png'), label: "Love it" },
    { id: 'pip-07', src: require('../../assets/stickers/pip-07.png'), label: "What?!" },
    { id: 'pip-08', src: require('../../assets/stickers/pip-08.png'), label: "Got it" },
  ],
};
export const stickerById = new Map(Object.values(STICKERS).flat().map((s) => [s.id, s]));
